services:
  p5live:
    build: .
    ports:
      - "5002:5001"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules
            - package.json
            - package-lock.json
        - action: rebuild
          path: ./package.json
